import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import "./globals.css";

//Third Party Imports
import { SessionProvider } from "next-auth/react";
import PageLoader from "../components/ui/PageLoader";

//Local Imports
/* import FacebookSDK from "@/components/ui/FacebookSDK";
 */
export const metadata = {
  title: "École arménienne Sourp Hagop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={{ fontFamily: "Roboto, sans-serif" }}>
        {/* <FacebookSDK /> */}
        <SessionProvider>
          <PageLoader>
            {children}
          </PageLoader>
        </SessionProvider>      
      </body>
    </html>
  );
}
