import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import "@/app/globals.css";

import { Noto_Sans_Armenian } from "next/font/google";
import localFont from "next/font/local";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { setRequestLocale } from "next-intl/server";
import { notFound } from "next/navigation";
import { headers } from "next/headers";
import { SessionProvider } from "next-auth/react";
import PageLoader from "@/components/ui/PageLoader";
import CookieNotice from "@/components/ui/CookieNotice";
import { routing } from "@/i18n/routing";
import { getPathname } from "@/i18n/navigation";
import { SITE_URL } from "@/lib/site-url";
import { ARMENIAN_CONTENT_TRANSLATED } from "@/lib/armenian-content-status";

const SITE_TITLE = "École arménienne Sourp Hagop";
const SITE_DESCRIPTION = "Generated by create next app";

// Loaded with both subsets in one call so the browser's own unicode-range
// based font loading does the work: a French page's glyphs are all within
// the "latin" @font-face's range and never touch the "armenian" file, and
// vice versa. Weight is "variable" (not a fixed list) because the site's
// existing CSS already applies several different numeric font-weight
// values (300, 390, 600) to --primary-ff/--secondary-ff - a handful of
// static weights would force the browser to synthesize the ones that don't
// match a shipped file, exactly the kind of mismatch this is meant to avoid.
const notoSansArmenian = Noto_Sans_Armenian({
  subsets: ["latin", "armenian"],
  weight: "variable",
  variable: "--font-armenian",
  display: "swap",
});

// next/font/google has no Google `text=` subsetting option anywhere in its
// options surface (checked the installed source: validate-google-font-
// function-call.js, get-google-fonts-url.js, loader.js - none accept or
// forward a `text` key). The full Armenian face above is unicode-range-split
// and only fetched where a page renders an Armenian glyph - but today that
// includes every French page, because the "ՀԱՅ" language-switcher label
// (topNav.module.css .langOption) is the one piece of live Armenian text
// that's always on screen. That forces a 26,816 B fetch for 3 glyphs.
// This is a manually pre-generated subset (fonttools/hb-subset equivalent,
// via the `subset-font` package, run once - not a build dependency) of the
// exact same Noto Sans Armenian file, cut down to only Հ/Ա/Յ: 1,988 B.
// It's applied ahead of the full face in the switcher's font stack (see
// .langOption in topNav.module.css), so the browser's unicode-range
// resolution picks this file for those 3 characters instead of the full
// one. The full face stays as a further fallback in that same stack for
// robustness (see comment there), but is no longer reachable from any
// French page: nothing else on those pages renders Armenian glyphs, so it
// is now fetched only where real Armenian content actually appears.
const armenianLabelSubset = localFont({
  src: "../fonts/armenian-label-subset.woff2",
  variable: "--font-armenian-label",
  display: "swap",
});

// Strips a resolved request path down to the locale-neutral route path
// shared by every locale's version of a page (e.g. "/hy/historique" and
// "/historique" both resolve to "/historique"). Generated from
// routing.locales/defaultLocale rather than hardcoding which locale
// carries a prefix, so this keeps working unchanged if that config ever
// changes.
function getCanonicalPath(pathname) {
  for (const locale of routing.locales) {
    if (locale === routing.defaultLocale) continue;
    const prefix = `/${locale}`;
    if (pathname === prefix || pathname.startsWith(`${prefix}/`)) {
      const stripped = pathname.slice(prefix.length);
      return stripped === "" ? "/" : stripped;
    }
  }
  return pathname;
}

export async function generateMetadata({ params }) {
  const { locale } = await params;
  const headersList = await headers();
  const canonicalPath = getCanonicalPath(headersList.get("x-pathname") ?? "/");

  // Self-referencing, bidirectional hreflang alternates: every locale's
  // version of a page lists every locale's URL (including its own), built
  // purely from routing.locales/getPathname - never hand-written per page.
  const languages = Object.fromEntries(
    routing.locales.map((l) => [l, `${SITE_URL}${getPathname({ href: canonicalPath, locale: l })}`])
  );

  return {
    metadataBase: new URL(SITE_URL),
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
    alternates: {
      canonical: languages[locale],
      languages: {
        ...languages,
        "x-default": languages[routing.defaultLocale],
      },
    },
    // See lib/armenian-content-status.js for what flips this and who
    // decides - not touched by hreflang/sitemap shipping (phase 7, step 3)
    // or by anything else in this file.
    ...(locale !== routing.defaultLocale && !ARMENIAN_CONTENT_TRANSLATED
      ? { robots: { index: false, follow: false } }
      : {}),
  };
}

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({ children, params }) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  setRequestLocale(locale);

  return (
    <html
      lang={locale}
      className={`${notoSansArmenian.variable} ${armenianLabelSubset.variable}`}
    >
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <title>{SITE_TITLE}</title>
        <meta name="description" content={SITE_DESCRIPTION} />
      </head>
      <body className="body-font">
        <NextIntlClientProvider>
          <SessionProvider>
            <PageLoader>
              {children}
            </PageLoader>
            <CookieNotice />
          </SessionProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}