import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import "@/app/globals.css";

import { hasLocale, NextIntlClientProvider } from "next-intl";
import { setRequestLocale } from "next-intl/server";
import { notFound } from "next/navigation";
import { SessionProvider } from "next-auth/react";
import PageLoader from "@/components/ui/PageLoader";
import { LangProvider } from "@/components/display/LangContext";
import { routing } from "@/i18n/routing";

export const metadata = {
  title: "École arménienne Sourp Hagop",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({ children, params }) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  setRequestLocale(locale);

  return (
    <html lang={locale}>
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={{ fontFamily: "Roboto, sans-serif" }}>
        <NextIntlClientProvider>
          <SessionProvider>
            <LangProvider>
              <PageLoader>
                {children}
              </PageLoader>
            </LangProvider>
          </SessionProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}