import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import "@/app/globals.css";

import { Noto_Sans_Armenian } from "next/font/google";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { setRequestLocale } from "next-intl/server";
import { notFound } from "next/navigation";
import { SessionProvider } from "next-auth/react";
import PageLoader from "@/components/ui/PageLoader";
import { routing } from "@/i18n/routing";

const SITE_TITLE = "École arménienne Sourp Hagop";
const SITE_DESCRIPTION = "Generated by create next app";

// Loaded with both subsets in one call so the browser's own unicode-range
// based font loading does the work: a French page's glyphs are all within
// the "latin" @font-face's range and never touch the "armenian" file, and
// vice versa. Weight is "variable" (not a fixed list) because the site's
// existing CSS already applies several different numeric font-weight
// values (300, 390, 600) to --primary-ff/--secondary-ff - a handful of
// static weights would force the browser to synthesize the ones that don't
// match a shipped file, exactly the kind of mismatch this is meant to avoid.
const notoSansArmenian = Noto_Sans_Armenian({
  subsets: ["latin", "armenian"],
  weight: "variable",
  variable: "--font-armenian",
  display: "swap",
});

export async function generateMetadata({ params }) {
  const { locale } = await params;
  return {
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
    // TEMPORARY (removed in phase 7 when hreflang + the sitemap land):
    // the non-default locale has 0% real translation coverage today -
    // every hy page currently serves French content through the GROQ
    // fallback (see docs/adr/0001-architecture-i18n.md, section 6). A
    // real visitor sees a normal page; a search engine would just see
    // duplicate content under the wrong-language URL. Once hreflang and
    // the sitemap ship, indexing can be judged page-by-page as
    // translations land, instead of blocked for the whole locale.
    ...(locale !== routing.defaultLocale
      ? { robots: { index: false, follow: false } }
      : {}),
  };
}

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({ children, params }) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  setRequestLocale(locale);

  return (
    <html lang={locale} className={notoSansArmenian.variable}>
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <title>{SITE_TITLE}</title>
        <meta name="description" content={SITE_DESCRIPTION} />
      </head>
      <body className="body-font">
        <NextIntlClientProvider>
          <SessionProvider>
            <PageLoader>
              {children}
            </PageLoader>
          </SessionProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}